apiVersion: v2
description: A Helm chart for the Platform Prototype App
name: dapr-testing-app
version: v0.1.0
type: application
appVersion: v0.1.0
maintainers:
  - name: lburgazzoli
    email: lburgazzoli@gmail.com
    url: http://lburgazzoli.github.io
home: http://github.com/lburgazzoli/dapr-testing-app
keywords:
  - cloudnative
  - example
  - cd
  - kubernetes
  - tutorial
