name: Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: "Set up Ko"
        uses: ko-build/setup-ko@v0.6
      - name: "Login to GitHub Container registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: "Publish"
        run: |
          ko build --bare --tag-only main.go
